### ISSUE TITLE
crash on load 1.14.4(fabric)

### ISSUE THREAD

**Issue by SDUBZ** [Codasylph/Demesne#11]
fabric: 
fabric-loader-0.4.8+build.157-1.14.4
Fabric API 0.3.0+build.200
demesne: Demesne 1.14.3-2.2.9-FABRIC
cotton: Cotton 1.0.0-rc.2
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.1
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		cotton-commons: Cotton Commons 1.0.0-rc.1
		cotton-config: Cotton Config 1.0.0-rc.1
		cotton-datapack: Cotton Datapack 1.0.0-rc.1
		cotton-energy: Cotton Energy 1.5.0+1.14.3
		cotton-logging: Cotton Logging 1.0.0-rc.1
		cotton-player-events: Cotton Player Events 1.0.0-rc.2
		cotton-resources: Cotton Resources 1.3.2+1.14.3
crash report:

[crash-2019-07-21_22.42.22-client.txt](https://github.com/Codasylph/Demesne/files/3422058/crash-2019-07-21_22.42.22-client.txt)

**Comment by JustJinxed** [comment]
Needs an update for the cotton suite. 
I'd be willing to help, if you're willing to take on a contributor.

**Comment by SDUBZ** [comment]
@Codasylph is there is a new update coming soon , i know you get real busy just asking

**Comment by Codasylph** [comment]
It actually needs an update to minecraft 1.14.4. (unless 1.14.3 and 1.14.4 are otherwise compatible, I haven't looked yet.)  I have been out of town for a bit.  I will be looking at updating later this week.  I do apologize for the delay, but y'know, life and stuff.
