### ISSUE TITLE
Codechickenlib compatibility issues

### ISSUE THREAD

**Issue by Zack7292** [Codasylph/Demesne#12]
Hi, i was testing around your mod with a bunch of other mod including codechickenlib and Vanilla fix. suddendly, when i was walking around with my dousing orb and it suddently crash. i really want to put this mod into a big modpack then im making (not evenabout to be in alpha state) also, i can't creat the domesne, surely due to a compatibility probleme qith the same mod. hope tath will be fix!
  
version of the mod: last of the 1.12.2 (1.2.7)
[Here my crash log :D](https://anotepad.com/notes/ngdmcr)

**Comment by Codasylph** [comment]
This is not actually an issue with codechickenlib, this is a bug in the mod that i am aware of and have a fix for but life got in the way of me shipping an update, so let me just go do that now.

**Comment by Zack7292** [comment]
cool  :)
