### ISSUE TITLE
Crash upon placing Hopper Grinder (with OptiFine installed)

### ISSUE THREAD

**Issue by BigDemoband** [Codasylph/Demesne#2]
Heyo. Was running my Minecraft world and placed a Hopper Grinder next to a power level four demesne when my game crashed with the issue linked to the Grinder itself.  When I tried to reboot the world, it gave me roughly the same error. The error is detailed here: https://paste.dimdev.org/zaharecile.mccrash

I'll be able to re-access my world again thanks to a few other mods I've got set up there and I can just disable it to get back in, but this is a lovely mod I'd like to be able to use.

**Comment by Codasylph** [comment]
After some testing I can say definitively that this is a compatibility issue with OptiFine. Now, whether there's anything I can do about it... eh. I'm going to look into it.

**Comment by BigDemoband** [comment]
Aw, jeez. Nice to know what the source is, shame it's OptiFine. I run that to make Minecraft usable with the amount of mods I've got in there (as I'm sure you saw in the list), but thanks for letting me know it's the source of the problem.

EDIT: After removing OptiFine and re-adding Demesne, I continued to run into the same problem. The strange thing is, once I re-added Demesne, the Hopper was back in its original spot... and I proceeded to get the same crash. It's detailed here: https://paste.dimdev.org/omeredodol.mccrash

**Comment by Codasylph** [comment]
It's actually not the same error, and I would _assume_ it is related to the fact that Minecraft started to render that particular grinder with OptiFine installed and now its not.  I wish I could be more helpful, but frankly Minecraft's rending pipeline is ever so slightly arcane to me, and what OptiFine does to it is *very* arcane to me.  I know from testing that the mod works on a fresh world that Optifine has never touched, and that in installing OptiFine causes the IndexOutOfBoundsException you first encountered any time Minecraft tries to render a .obj in a tile entity special renderer (which happens in the grinding hopper, and the alchemist's worktable.) My current plan for dealing with this is alternate models/animations for those two blocks that only use .obj for static parts of the block. Which will have the slightly ironic side effect that those blocks will be less pretty with OptiFine installed.

**Comment by BigDemoband** [comment]
Hey, you responding to the error at all and letting me know what's going on is helpful! Honestly I had a hunch that OptiFine was still messing with stuff, but I'm not a coder and didn't want to make assumptions. Still, thank you for working to make the objects work with OptiFine installed. I very much love your mod and I look forward to being able to use it!

**Comment by Codasylph** [comment]
I've updated Demesne so that it detects if OptiFine is loaded and doesn't render certain things if it is.  This isn't my final solution, because I don't like that it makes those blocks uglier, but at least it won't crash!

**Comment by BigDemoband** [comment]
Thank you!
