### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by NomSTeh** [Codasylph/Demesne#4]
Launched game and once it loaded the main menu got this crash
https://paste.dimdev.org/ahopizepac.mccrash

**Comment by Codasylph** [comment]
Looking into this, although based on which mixin caused the crash my gut says this  is optifine related. :(

**Comment by Codasylph** [comment]
Yep. Initial testing shows this is a conflict with OptiFabric and/or OptiFine.  Probably OptiFine itself, because that's how my life goes.

**Comment by Codasylph** [comment]
The offending mixin is being removed in the next version in favor of a (hopefully optifine friendly) jmx dependency.  Right now what I need JMX to do is bugged (yay!) but in a non-fatal way, and that mod dev is working on it.
