### ISSUE TITLE
Crash when placing blood needle over an altar already linked 1.12.2

### ISSUE THREAD

**Issue by Akaruz64** [Codasylph/Demesne#5]
I know it maybe was a stupid thing to do, but since we got no ingame guide, i just thought that you needed to link your second blood needle to the altar in order to use it

Crashlog:
https://paste.dimdev.org/novokasima.mccrash

Lastes 1.12.2 version

**Comment by Codasylph** [comment]
omg, thank you so much for telling me which version you were using!  It might be a silly thing to do, but I certainly don't want your game crashing over it! will update to fix this!

Also, I realize there is no *in game* doc, but just so you know, there is a wiki https://demesne.fandom.com/wiki/Demesne_Wiki which is specifically for the 1.12.2 version of the game.  And a few intro videos, although for those you have to sit through me talking. :P

**Comment by Codasylph** [comment]
Ok, I did some testing, and I cannot reproduce this. I did put in some extra null checking for safety for the next build, but I'd feel better claiming I fixed it if I could see the problem first hand to begin with.  What mod pack are you using? Maybe their's some sort of conflict there.

**Comment by Akaruz64** [comment]
Hey,
Yeah, read the wiki and saw the videos several times, but i keep forgetting stuff (that´s me actually) and really hate the need to alt + tab to watch that part of the video, no pressure thou, make´s me feel like old time minecraft, when you needed to open the wiki to see the recipes
On the issue thou, i´m not a modpack person, i just download whatever catches my interest and provided it doesn't break my world, just add it to the list so, not much to go on with except for the crash log I uploaded, most likely some conflict with Vanilla Fix or Better with Mods, they usually conflict with a lot of stuff, at least on the ticking block entity (had a lot of those already)

Anyway, i managed to fix it by removing the mod, loading the world, and just installing it again, and fortunately it only removed the altar, the rest of the blocks, (Lava Tank) reappeared on the same spot they were, also the demesne so nothing lost,  feel free to just close the issue for the moment, i know i won't try that again.

Thanks and keep up the good work!
Cheers.

**Comment by ProsperCraft** [comment]
We just had this NPE crash on our dedicated server on version  demesne-1.12.2-1.2.7

When the player went to try it again, it didn't crash a second time.

He said "server crashed when adding a blooded bone needle to a marble tier altar from demesne to attune it to myself"

https://paste.fedoraproject.org/paste/7N4zmcRwaIjjgWJoNsTewA

I see there was an update today, I will update.

Modpack - https://www.curseforge.com/minecraft/modpacks/ancient-towncraft

**Comment by jbettini** [comment]
- [ ] ss
