### ISSUE TITLE
Crash when placing forge in a certain direction

### ISSUE THREAD

**Issue by NomSTeh** [Codasylph/Demesne#9]
https://paste.dimdev.org/yogipeyani.sql

**Comment by Codasylph** [comment]
You sure are good at finding my bugs. :P
Thank you! Pretty sure I know just from the report what went wrong, this will be fixed in the next update. Although I don't know if I'll be able to upload it today because CF moderators still haven't approved my Fabric only project. :/

**Comment by Codasylph** [comment]
So, I have fixed this, but CurseForge still hasn't approved my separated project for Demesne for Fabric, so in the mean time, here's a drop box link to the current version of the mod, if you like: https://www.dropbox.com/s/5dksxzpzujuo4t9/demesne-1.14.3-2.2.9-FABRIC.jar?dl=0, i'll leave it up till CF approves the project at least.
